export const skills = [
  "Next.js",
  "React",
  "React Native",
  "TypeScript",
  "Node.js",
  "Docker",
  "Express.js",
  "Tanstack Query",
  "Figma",
  "Zod",
  "Javascript",
  "PostgreSQL",
  "MongoDB",
  "Redux",
  "Prisma",
  "React Hook Form",
  "Shadcn UI",
  "Git",
  "Tailwind CSS",
  "Framer Motion",
  "CI/CD Pipeline",
  "Vercel",
  "RESTful API",
  "Auth.js",
  "Firebase",
];
